const SPORTS=[{id:"nfl",label:"NFL"},{id:"ncaaf",label:"College football"},{id:"nba",label:"NBA"},{id:"mlb",label:"MLB"},{id:"nhl",label:"NHL"},{id:"other",label:"Other"}];
const DEFAULT_SEASON_GAMES={nfl:17,ncaaf:12,nba:82,mlb:162,nhl:82};
const $=(id)=>document.getElementById(id); let bets=[];
function normalizeBets(data){if(Array.isArray(data))return data.filter(Boolean);if(!data||typeof data!=="object")return[];return data.kind?[data]:Object.values(data).filter(v=>v&&v.kind)}
function sportLabel(id){return(SPORTS.find(s=>s.id===id)||{}).label||id||"Other"} function kindLabel(kind){return{record:"Team record",parlay:"Parlay",award:"Award",game:"Game",future:"Future"}[kind]||"Player prop"}
function pct(bet){const t=Number(bet?.target)||1;return Math.max(0,Math.min(100,(Number(bet?.current)||0)/t*100))} function parlayPct(bet){const l=Array.isArray(bet?.legs)?bet.legs:[];return l.length?l.reduce((s,x)=>s+pct(x),0)/l.length:0}
function solidColor(p){const x=Math.max(0,Math.min(100,Number(p)||0))/100;let r,g,b;if(x<.5){const t=x/.5;r=192;g=Math.round(57+t*139);b=Math.round(43-t*28)}else{const t=(x-.5)/.5;r=Math.round(241-t*202);g=Math.round(196-t*22);b=Math.round(15+t*81)}return`rgb(${r}, ${g}, ${b})`}
function escapeHtml(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))} function currency(v){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v)||0)} function num(v){return new Intl.NumberFormat("en-US",{maximumFractionDigits:1}).format(Number(v)||0)}
function bar(p,small=false){const x=Math.max(0,Math.min(100,Number(p)||0));return`<div class="bar${small?" small":""}"><span style="width:${x}%;background:${solidColor(x)}"></span></div>`}
function selectedFilters(){return{user:$("filterUser")?.value||"all",sport:$("filterSport")?.value||"all",kind:$("filterType")?.value||"all",timeline:$("filterTimeline")?.value||"all",status:$("filterStatus")?.value||"all"}}
function getFilteredBets(){const f=selectedFilters();return bets.filter(b=>b&&!b.template&&(f.user==="all"||(b.user||"Unassigned")===f.user)&&(f.sport==="all"||b.sport===f.sport)&&(f.kind==="all"||(b.kind||"player-prop")===f.kind)&&(f.timeline==="all"||b.timeline===f.timeline)&&(f.status==="all"||(b.status||"open")===f.status))}
function fillSports(){$("filterSport").innerHTML=`<option value="all">All sports</option>`+SPORTS.map(s=>`<option value="${s.id}">${s.label}</option>`).join("")} function fillUsers(){const selected=$("filterUser").value||"all",users=[...new Set(bets.map(b=>b.user||"Unassigned"))].sort();$("filterUser").innerHTML=`<option value="all">All users</option>`+users.map(u=>`<option value="${escapeHtml(u)}">${escapeHtml(u)}</option>`).join("");$("filterUser").value=users.includes(selected)?selected:"all"}
function render(){const filtered=getFilteredBets();$("statusLine").textContent=`${filtered.length} bet(s)`;$("betList").innerHTML=filtered.map(b=>{const k=b.kind||"player-prop",p=k==="parlay"?parlayPct(b):pct(b),money=b.notes||"",summary=k==="record"?`${Number(b.current)||0}-${Number(b.losses)||0}${Number(b.ties)?`-${Number(b.ties)}`:""} · target ${Number(b.target)} wins`:k==="parlay"?`${(b.legs||[]).length} legs · all must hit`:`${Number(b.current)||0} / ${Number(b.target)}`;const legs=k==="parlay"?`<div class="legs">${(b.legs||[]).map(l=>{const x=pct(l);return`<div class="leg"><p class="leg-title">${escapeHtml(l.subject)} · ${escapeHtml(l.stat||"")}</p>${bar(x,true)}<p class="meta">${x.toFixed(0)}% · ${Number(l.current)||0} / ${Number(l.target)}</p></div>`}).join("")}</div>`:"";return`<article class="card"><div class="card-top"><div><p class="title">${escapeHtml(b.desc)}</p><p class="meta">${escapeHtml(b.subject||"")}${money?" · "+escapeHtml(money):""}</p></div><div class="chips"><span class="chip">${escapeHtml(b.user||"Unassigned")}</span><span class="chip">${sportLabel(b.sport)}</span><span class="chip">${kindLabel(k)}</span><span class="chip">${b.status||"open"}</span></div></div>${bar(p)}<p class="meta">${p.toFixed(0)}% · ${summary}</p>${legs}</article>`}).join("")||`<p class="meta">No bets found.</p>`}
function isBinary(b){return["award","future"].includes(b?.kind)} function seasonGames(e){return Number(e?.seasonGames)||DEFAULT_SEASON_GAMES[e?.sport]||17} function winDirection(e){const text=`${e?.desc||""} ${e?.notes||""}`.toLowerCase();return /\bunder\b/.test(text)?"under":"over"}
function reportEntries(b){if(isBinary(b))return[];if(b.kind!=="parlay")return[{...b,parentId:null}];const legs=Array.isArray(b.legs)?b.legs:[],usable=legs.filter(l=>!isBinary(l)),stake=(Number(b.stake)||0)/(usable.length||1),payout=(Number(b.payout)||0)/(usable.length||1);return usable.map((l,i)=>({...l,id:`${b.id}-leg-${i}`,parentId:b.id,parentDesc:b.desc||"Parlay",isParlayLeg:true,stake,payout,user:b.user}))}
function gameCount(e){const given=Number(e?.gamesPlayed);if(Number.isFinite(given)&&given>0)return given;return(Number(e?.current)||0)>0?1:0}
function metric(e){const target=Number(e?.target)||0;if(!target)return null;const current=Number(e?.current)||0,kind=e?.kind||"player-prop",raw=Math.max(0,Math.min(100,current/target*100));const games=gameCount(e),season=seasonGames(e),required=target/season,actual=games?current/games:0,paceRatio=games?actual/required:0;let score=0,detail="";
if(kind==="record"){const direction=winDirection(e),losses=Number(e?.losses)||0,played=current+losses+(Number(e?.ties)||0);if(direction==="under"){const maxWins=Math.max(0,target-1),allowedLosses=Math.max(0,season-maxWins);const lossProgress=allowedLosses?losses/allowedLosses:0;const remainingCapacity=season-played;const stillPossible=current+remainingCapacity<=maxWins;score=stillPossible?Math.max(0,Math.min(100,lossProgress*100+(played/season)*20)):0;detail=`Under ${target} wins · ${current}-${losses} record`}else{score=raw;detail=`Over ${target-1} wins · ${current}-${losses} record`}}
else{score=games?Math.max(0,Math.min(100,raw*.4+Math.min(100,paceRatio*100)*.6)):0;detail=games?`${num(actual)}/game vs ${num(required)}/game required`:`${num(current)} / ${num(target)}`}
const payout=Number(e?.payout)||0,stake=Number(e?.stake)||0;return{raw,games,season,required,actual,paceRatio,score,payout,stake,implied:payout*score/100,detail}}
function reportName(e){return e.isParlayLeg?`${e.subject||"Leg"} · ${e.stat||""}`:(e.desc||e.subject||"Bet")} function reportFilterLabel(){const f=selectedFilters(),p=[];if(f.user!=="all")p.push(f.user);if(f.sport!=="all")p.push(sportLabel(f.sport));if(f.kind!=="all")p.push(kindLabel(f.kind));return p.length?p.join(" · "):"All eligible bets"} function reportError(msg){const n=$("reportError");if(n){n.hidden=!msg;n.textContent=msg||""}}
function chartRow(e,m){return`<div class="chart-item"><div class="chart-row"><span class="chart-name" title="${escapeHtml(reportName(e))}">${escapeHtml(reportName(e))}</span><div class="chart-track"><div class="chart-fill" style="width:${m.score}%;background:${solidColor(m.score)}"></div></div><span class="chart-pct">${m.score.toFixed(0)}%</span></div><p class="chart-detail">${escapeHtml(m.detail)} · implied value ${currency(m.implied)} of ${currency(m.payout)}</p></div>`}
function renderReport(){const panel=$("reportPanel");if(!panel)throw new Error("The report panel is missing from index.html.");panel.hidden=false;reportError("");const filtered=getFilteredBets(),all=filtered.flatMap(reportEntries).map(e=>({entry:e,metric:metric(e)})).filter(x=>x.metric);$("reportTitle").textContent=reportFilterLabel();if(!all.length){$("reportStats").innerHTML=`<div class="stat-box"><span>Eligible entries</span><strong>0</strong></div>`;$("reportPercent").textContent="—";$("reportBar").style.width="0%";$("reportBar").style.background=solidColor(0);$("reportNote").textContent="No player props, team-win totals, or parlay legs match the selected filters. Award and future tickets are excluded.";$("reportChart").innerHTML="";return}
const payoutTotal=all.reduce((s,x)=>s+x.metric.payout,0),progress=payoutTotal?all.reduce((s,x)=>s+x.metric.score*x.metric.payout,0)/payoutTotal:all.reduce((s,x)=>s+x.metric.score,0)/all.length,stake=all.reduce((s,x)=>s+x.metric.stake,0),value=all.reduce((s,x)=>s+x.metric.implied,0);$("reportStats").innerHTML=`<div class="stat-box"><span>Eligible entries</span><strong>${all.length}</strong></div><div class="stat-box"><span>Tickets selected</span><strong>${filtered.length}</strong></div><div class="stat-box"><span>Allocated stake</span><strong>${currency(stake)}</strong></div><div class="stat-box"><span>Implied payout value</span><strong>${currency(value)}</strong></div>`;$("reportPercent").textContent=`${progress.toFixed(0)}%`;$("reportBar").style.width=`${progress}%`;$("reportBar").style.background=solidColor(progress);$("reportNote").textContent="Payout-weighted pace score. Player props combine completion (40%) and required pace (60%). Team win bets respect over/under direction. Futures and awards are excluded.";
const singles=all.filter(x=>!x.entry.parentId).sort((a,b)=>b.metric.score-a.metric.score),groups=new Map();all.filter(x=>x.entry.parentId).forEach(x=>{if(!groups.has(x.entry.parentId))groups.set(x.entry.parentId,[]);groups.get(x.entry.parentId).push(x)});let html=singles.map(x=>chartRow(x.entry,x.metric)).join("");for(const [id,legs] of groups){const avg=legs.reduce((s,x)=>s+x.metric.score,0)/legs.length,payout=legs.reduce((s,x)=>s+x.metric.payout,0),implied=legs.reduce((s,x)=>s+x.metric.implied,0),name=legs[0].entry.parentDesc||"Parlay";html+=`<details class="parlay-bucket"><summary><div class="parlay-summary"><span class="chart-name" title="${escapeHtml(name)}">${escapeHtml(name)} · ${legs.length} legs</span><div class="chart-track"><div class="chart-fill" style="width:${avg}%;background:${solidColor(avg)}"></div></div><span class="chart-pct">${avg.toFixed(0)}%</span></div><p class="chart-detail">Parlay bucket · implied value ${currency(implied)} of ${currency(payout)} · click to show legs</p></summary><div class="parlay-legs">${legs.sort((a,b)=>b.metric.score-a.metric.score).map(x=>chartRow(x.entry,x.metric)).join("")}</div></details>`}$("reportChart").innerHTML=html}
function openReport(){try{renderReport();$("reportPanel").scrollIntoView({behavior:"smooth",block:"start"})}catch(e){const p=$("reportPanel");if(p){p.hidden=false;reportError(`Chart Report could not finish: ${e.message}`)}else $("statusLine").textContent=`Chart Report error: ${e.message}`;console.error(e)}}
async function loadBets(){for(const url of[`https://raw.githubusercontent.com/ZacheryTaylor/bet-tracker/main/data/bets.json?t=${Date.now()}`,`data/bets.json?t=${Date.now()}`])try{const r=await fetch(url);if(!r.ok)continue;bets=normalizeBets(await r.json());fillUsers();render();return}catch(e){console.warn(e)}$("statusLine").textContent="Could not load data/bets.json"}
async function refreshRecord(b){if(!window.TeamRecord)throw new Error("Team record helper did not load");const r=await fetch("https://site.api.espn.com/apis/v2/sports/football/nfl/standings");if(!r.ok)throw new Error(`Standings ${r.status}`);const record=window.TeamRecord.findOverallRecord(await r.json(),b.subject);if(!record)throw new Error(`No overall record found for ${b.subject}`);b.current=record.wins;b.losses=record.losses;b.ties=record.ties;if((b.status||"open")==="open"&&pct(b)>=100)b.status="hit";return true}
async function refreshOne(b){if(!b||isBinary(b))return false;if(b.kind==="record")return refreshRecord(b);if(b.kind==="parlay"){let u=false;for(const l of b.legs||[]){l.sport=l.sport||b.sport||"nfl";if(await window.EspnPlayer.refreshPlayer(l))u=true}if(u&&(b.legs||[]).every(l=>pct(l)>=100))b.status="hit";return u}return window.EspnPlayer.refreshPlayer(b)}
$("refreshBtn").addEventListener("click",async()=>{if(!window.EspnPlayer||!window.TeamRecord){$("statusLine").textContent="Refresh helpers failed to load.";return}$("refreshBtn").disabled=true;$("statusLine").textContent="Refreshing ESPN…";let updated=0;const missed=[];for(const b of bets)try{if(await refreshOne(b))updated+=1;else if(!isBinary(b))missed.push(b.desc||b.subject||b.id)}catch(_){missed.push(b.desc||b.subject||b.id)}render();if(!$("reportPanel").hidden)openReport();$("refreshBtn").disabled=false;$("statusLine").textContent=`Updated ${updated} bet(s).`+(missed.length?` Still empty: ${missed.slice(0,8).join("; ")}`:"")});
$("reportBtn").addEventListener("click",openReport);$("closeReportBtn").addEventListener("click",()=>{$("reportPanel").hidden=true});["filterUser","filterSport","filterType","filterTimeline","filterStatus"].forEach(id=>$(id).addEventListener("change",()=>{render();if(!$("reportPanel").hidden)openReport()}));fillSports();loadBets();
